#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/random c 1 8
mknod -m 666 /dev/urandom c 1 9
mknod -m 666 /dev/tty c 5 0
mknod -m 660 /dev/tty0 c 4 0
mknod -m 660 /dev/tty1 c 4 1
mknod -m 660 /dev/tty2 c 4 2
mknod -m 660 /dev/tty3 c 4 3
mknod -m 660 /dev/tty4 c 4 4
mknod -m 660 /dev/ttyS0 c 4 64

exec /sbin/init
