#!/bin/sh

ip link set lo up
ip link set eth0 up
ip link set eth1 up

udhcpc -b -i eth0 -s /etc/udhcpc.script

ip addr add 192.168.100.1/24 dev eth1
echo '
interface eth1
start 192.168.100.11
end   192.168.100.254
option dns 223.5.5.5
option subnet 255.255.255.0
option router 192.168.100.1
option lease 864000
' >/etc/udhcpd.conf
udhcpd /etc/udhcpd.conf

echo 1 >/proc/sys/net/ipv4/ip_forward
echo '
flush ruleset

table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        ip saddr 192.168.100.0/24 oif "eth0" masquerade
    }
}

table ip filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state vmap { established: accept, related: accept, invalid: drop }
        iifname vmap { lo: accept, eth0: jump input_eth0, eth1: jump input_eth1 }
    }
    chain input_eth0 {
        drop
    }
    chain input_eth1 {
        accept
    }
}
' | nft -f -
